name: talabna
description: Talbna is a versatile app that allows users to post and browse various categories such as jobs, real estate, cars, devices, and general services. Whether you're looking for a new career opportunity, a place to live, a car or any kind of service, Talbna has got you covered. Its user-friendly interface and search features make it easy to find what you're looking for and connect with potential buyers or sellers.

publish_to: 'none'

version: 2.2.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  awesome_flutter_extensions: ^1.2.0
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0
  get_it: ^8.0.2
  http: ^1.2.1
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.0.18
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.2.5
  location: ^8.0.0
  path: ^1.8.2
  http_parser: ^4.0.2
  mime: ^2.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.1.10
  # contacts_service: ^0.6.3  # Commented out as it was causing issues
  flutter_contacts: ^1.1.6
  flutter_image_compress: ^2.2.0
  image: ^4.0.15
  path_provider: ^2.0.14
  visibility_detector: ^0.4.0+2
  connectivity_plus: ^6.1.3
  google_fonts: ^6.2.0
  flutter_vector_icons: ^2.0.0
  share_plus: ^10.1.1
  intl_phone_field: ^3.1.0
  video_player: ^2.6.1
#  file_picker: ^8.1.3
  audioplayers: ^6.4.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  video_compress: ^3.1.2
  pull_to_refresh: ^2.0.0
  ffmpeg_kit_flutter: ^6.0.3
  font_awesome_flutter: ^10.6.0
  smooth_page_indicator: ^1.1.0
  flutter_facebook_auth_web: any
  google_sign_in_web: any
  image_picker_for_web: any
  shared_preferences_web: any
  restart_app: ^1.3.2
  lottie: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  app_links: ^6.4.0
  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.4.4
  # device_info_plus: ^9.0.0  # Commented out as it was causing issues

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  # Background color
  color: "#FFFFFF"
  # Background color for dark mode
  color_dark: "#121212"

  # Image source
  image: assets/images/splash_logo.png
  # Image for dark mode (optional)
  image_dark: assets/images/splash_logo_dark.png

  # For branding position
  branding: assets/images/branding.png
  # Branding for dark mode
  branding_dark: assets/images/branding_dark.png

  # Android 12+ specific settings
  android_12:
    # Image source for Android 12 splash screen
    image: assets/images/logo.png
    # Image for dark mode
    image_dark: assets/images/logo.png
    # Icon background color
    icon_background_color: "#FFFFFF"
    # Icon background color for dark mode
    icon_background_color_dark: "#121212"
    # Branding
    branding: assets/images/branding.png
    # Branding for dark mode
    branding_dark: assets/images/branding_dark.png

  # Disable the iOS status bar
  fullscreen: true

  # Web splash (for PWA)
  web: false

  # Add splash to all platforms
  android: true
  ios: true

  # Disable splash for desktop
  windows: false
  macos: false
  linux: false